x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Madrid
  _PIP_ADDITIONAL_REQUIREMENTS: "msal requests"
  AIRFLOW_UID: ${AIRFLOW_UID:-50000}
  AIRFLOW_GID: ${AIRFLOW_GID:-0}
  PYSPARK_PYTHON: python
  SPARK_LOCAL_DIRS: /opt/airflow/.spark

  #rutas para el pipeline
  DATA_DIR: /opt/airflow/data/v2
  WORK_DIR: /opt/airflow/work

  PBI_TENANT_ID: ${PBI_TENANT_ID:-}
  PBI_CLIENT_ID: ${PBI_CLIENT_ID:-}
  PBI_CLIENT_SECRET: ${PBI_CLIENT_SECRET:-}
  PBI_GROUP_ID: ${PBI_GROUP_ID:-}
  PBI_DATASET_ID: ${PBI_DATASET_ID:-}

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-init:
    build: .
    image: airflow-spark:2.9.2-py3.11
    entrypoint: /bin/bash
    command:
      - -c
      - |
        chown -R "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}" /opt/airflow
        exec /usr/bin/dumb-init -- \
        bash -c "airflow db init && \
                 airflow users create \
                   --username admin --password admin \
                   --firstname Air --lastname Flow \
                   --role Admin --email admin@example.com"
    environment:
      <<: *airflow-env
    user: "0:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./repo:/opt/airflow/repo
      - ./work:/opt/airflow/work         #unificado con windows se dejan los parquets
      - spark-local:/opt/airflow/.spark
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  airflow-webserver:
    image: airflow-spark:2.9.2-py3.11
    command: webserver
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./repo:/opt/airflow/repo
      - ./work:/opt/airflow/work
      - spark-local:/opt/airflow/.spark
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped

  airflow-scheduler:
    image: airflow-spark:2.9.2-py3.11
    command: scheduler
    environment:
      <<: *airflow-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./repo:/opt/airflow/repo
      - ./work:/opt/airflow/work
      - spark-local:/opt/airflow/.spark
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres-data:
  spark-local:
